swagger: "2.0"
info:
  description: Microservice for managing character data in online games
  title: Character Data Microservice
  version: 1.0.0
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
# Items
  /items:
    get:
      operationId: GetItems
      responses:
        200:
          description: List owned items
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"
  /item/{itemId}:
    parameters:
      - type: integer
        format: int64
        name: itemId
        in: path
        required: true
    get:
      operationId: GetItem
      responses:
        200:
          description: Returns specified item
          schema:
            $ref: "#/definitions/item"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"
# Skills
  /skills:
    get:
      operationId: GetSkills
      responses:
        200:
          description: Returns list of skills
          schema:
            type: array
            items:
              $ref: "#/definitions/skill"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"
  /skill/{skillId}:
    parameters:
      - type: integer
        format: int64
        name: skillId
        in: path
        required: true
    get:
      operationId: GetSkill
      responses:
        200:
          description: Returns specified skill
          schema:
            $ref: "#/definitions/skill"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"
    # Add post to add skills?         
# Class
  /class/{playerId}:
    parameters:
      - type: integer
        format: int64
        name: playerId
        in: path
        required: true
    get:
      operationId: GetClass
      responses:
        200:
          description: Returns players class
          schema:
            $ref: "#/definitions/class"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"
# Enemy stats
# Deaths
definitions:
# Items 
  item:
    type: object
    required:
      - identifier
      - description
    properties:
      identifier:
        type: integer
      description:
        type: string
# Skills
  skill:
    type: object
    required:
      - identifier
    properties:
      identifier:
        type: integer
      description:
        type: string
# Class
  class:
    type: object
    required:
      - description
    properties:
      identifier:
        type: integer
      description:
        type: string
      abilities:
        type: array
        items:
          $ref: "#/definitions/skill"
#Generic error
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
